rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - 2.0.0
 - 2.1
 - ree
 - rbx

before_install: git submodule update -i

script: bundle exec rake spec

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ree
    - rvm: rbx
